<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssessmentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('assessments')->delete();
        // Section 1
        DB::table('assessments')->insert([
            [
                'persona_id' => "1",
                'label' => "Orang yang bisa meyakinkan orang lain",
                'group' => "1",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Orang yang memiliki jiwa kompetitif",
                'group' => "1",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Orang yang penuh perhatiaan",
                'group' => "1",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Orang yang pandai mengendalikan dirinya",
                'group' => "1",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Orang yang senang menyemangati",
                'group' => "2",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Orang yang bisa bertindak cepat",
                'group' => "2",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Orang yang memperlakukan orang lain dengan baik",
                'group' => "2",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Orang yang cenderung menahan diri",
                'group' => "2",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Orang yang selalu bersemangat",
                'group' => "3",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Orang yang sangat mandiri",
                'group' => "3",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Orang yang memperlakukan orang lain dengan baik",
                'group' => "3",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Orang yang sensitif",
                'group' => "3",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Seorang penggerak",
                'group' => "4",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Seorang yang berpikir positif",
                'group' => "4",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Seorang yang terperencana",
                'group' => "4",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Seorang yang sabar",
                'group' => "4",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Seseorang yang menyenangkan",
                'group' => "5",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Seseorang yang pemberani",
                'group' => "5",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Seseorang yang terperinci",
                'group' => "5",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Seseorang yang peka dan bijaksana",
                'group' => "5",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Orang yang banyak bicara",
                'group' => "6",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Orang yang teguh pada pendirian",
                'group' => "6",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Orang yang bijaksana",
                'group' => "6",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Orang yang toleran",
                'group' => "6",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Suka bergurau dan membuat humor",
                'group' => "7",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Suka meyakinkan seseorang menggunakan fakta",
                'group' => "7",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Pantang menyerah",
                'group' => "7",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Tenang dan tidak gegabah",
                'group' => "7",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Seseorang yang suka bergaul",
                'group' => "8",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Seseorang yang suka menjadi penggerak",
                'group' => "8",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Seseorang yang memiliki apresiasi terhadap musik",
                'group' => "8",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Seseorang yang suka menghindari konflik",
                'group' => "8",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Seorang yang populer",
                'group' => "9",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Seseorang yang sangat produktif",
                'group' => "9",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Seseorang yang perfeksionis",
                'group' => "9",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Seseorang yang menyenangkan",
                'group' => "9",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Seseorang yang menarik",
                'group' => "10",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Seseorang yang mempunyai jiwa kepemimpinan",
                'group' => "10",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Seseorang yang menyukai tabel dan draft",
                'group' => "10",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Seseorang yang puas dengan yang dimiliki",
                'group' => "10",
                'section_id' => "1",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
        // Section 2
        DB::table('assessments')->insert([
            [
                'persona_id' => "1",
                'label' => "Periang",
                'group' => "1",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Suka berpetualang",
                'group' => "1",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Suka menganalisis",
                'group' => "1",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Mudah beradaptasi",
                'group' => "1",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Supel",
                'group' => "2",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Berkemauan keras",
                'group' => "2",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Rela berkorban",
                'group' => "2",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Penurut",
                'group' => "2",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Spontan",
                'group' => "3",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Tidak ragu",
                'group' => "3",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Terjadwal",
                'group' => "3",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Pemalu",
                'group' => "3",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Optimis",
                'group' => "4",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Blak-blakan",
                'group' => "4",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Tertib",
                'group' => "4",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Ringan tangan",
                'group' => "4",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Lucu",
                'group' => "5",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Tegas",
                'group' => "5",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Setia",
                'group' => "5",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Ramah",
                'group' => "5",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Selalu bersemangat",
                'group' => "6",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Percaya diri",
                'group' => "6",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Tertarik dengan hal-hal yang artistik",
                'group' => "6",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Konsisten",
                'group' => "6",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Inspiratif",
                'group' => "7",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Independent",
                'group' => "7",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Idealis",
                'group' => "7",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Tidak suka mengganggu",
                'group' => "7",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Demonstratif",
                'group' => "8",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Tegas",
                'group' => "8",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Suka dengan deep talk",
                'group' => "8",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Sarkastik",
                'group' => "8",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Enerjik",
                'group' => "9",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Pemimpin",
                'group' => "9",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Loyal",
                'group' => "9",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Pendengar",
                'group' => "9",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Periang",
                'group' => "10",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Berani",
                'group' => "10",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Sopan",
                'group' => "10",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Stabil",
                'group' => "10",
                'section_id' => "2",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
        // Section 3
        DB::table('assessments')->insert([
            [
                'persona_id' => "1",
                'label' => "Tukang pamer",
                'group' => "1",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Sok berkuasa",
                'group' => "1",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Canggung",
                'group' => "1",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Suka melamun",
                'group' => "1",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Tidak disiplin",
                'group' => "2",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Apatis",
                'group' => "2",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Menyimpan amarah",
                'group' => "2",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Ogah-ogahan",
                'group' => "2",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Suka mengulang cerita",
                'group' => "3",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Suka menentang",
                'group' => "3",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Mudah tersinggung",
                'group' => "3",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Enggan",
                'group' => "3",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Pelupa",
                'group' => "4",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Terang-terangan",
                'group' => "4",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Rewel",
                'group' => "4",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Penakut",
                'group' => "4",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Suka menginterupsi",
                'group' => "5",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Tidak sabaran",
                'group' => "5",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Mudah merasa terancam",
                'group' => "5",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Ragu-ragu",
                'group' => "5",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Tidak terduga",
                'group' => "6",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Tidak peduli",
                'group' => "6",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Tidak populer",
                'group' => "6",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Tidak terlibat",
                'group' => "6",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Tidak konsisten",
                'group' => "7",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Keras kepala",
                'group' => "7",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Sulit puas",
                'group' => "7",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Peragu",
                'group' => "7",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Memenuhi keinginan orang lain",
                'group' => "8",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Sombong",
                'group' => "8",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Pesimis",
                'group' => "8",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Datar",
                'group' => "8",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Mudah marah",
                'group' => "9",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Argumentatif",
                'group' => "9",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Terasing",
                'group' => "9",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Tanpa tujuan",
                'group' => "9",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Naif",
                'group' => "10",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Nekad",
                'group' => "10",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Bersikap negatif",
                'group' => "10",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Tak acuh",
                'group' => "10",
                'section_id' => "3",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
        // Section 4
        DB::table('assessments')->insert([
            [
                'persona_id' => "1",
                'label' => "Orang yang selalu ingin dipuji",
                'group' => "1",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Orang yang merasa pekerjaan adalah segala-galanya",
                'group' => "1",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Orang yang sering membutuhkan waktu untuk sendiri",
                'group' => "1",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Orang yang selalu merasa cemas",
                'group' => "1",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Banyak bicara",
                'group' => "2",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Tidak peka",
                'group' => "2",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Terlalu sensitif",
                'group' => "2",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Gentar",
                'group' => "2",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Tidak teratur",
                'group' => "3",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Mendominasi",
                'group' => "3",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Mudah merasa tertekan",
                'group' => "3",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Peragu",
                'group' => "3",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Orang yang mudah berubah pikiran",
                'group' => "4",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Orang yang tidak toleran",
                'group' => "4",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Orang yang egois",
                'group' => "4",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Orang yang tidak peduli ini atau itu",
                'group' => "4",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Orang yang cenderung berantakan",
                'group' => "5",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Orang yang suka memanipulatif",
                'group' => "5",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Orang yang mudah murung",
                'group' => "5",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Orang yang suka mengomel diam-diam ketika tertekan",
                'group' => "5",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Orang yang sangat ingin menjadi pusat perhatian",
                'group' => "6",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Orang yang tidak mudah dibujuk",
                'group' => "6",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Orang yang tidak mudah percaya",
                'group' => "6",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Orang yang bergeraknya lambat",
                'group' => "6",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Orang yang memiliki suara yang besar",
                'group' => "7",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Orang yang tidak ragu berkata jujur",
                'group' => "7",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Orang yang butuh banyak waktu sendiri",
                'group' => "7",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Orang yang cenderung pemalas",
                'group' => "7",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Kurang fokus",
                'group' => "8",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Pemarah",
                'group' => "8",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Mudah curiga",
                'group' => "8",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Malas-malasan",
                'group' => "8",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Mudah bosan",
                'group' => "9",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Gegabah",
                'group' => "9",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Pendendam",
                'group' => "9",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Berat hati",
                'group' => "9",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "1",
                'label' => "Plin-plan",
                'group' => "10",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "2",
                'label' => "Licik",
                'group' => "10",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "3",
                'label' => "Kritis",
                'group' => "10",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'persona_id' => "4",
                'label' => "Menghindari konflik",
                'group' => "10",
                'section_id' => "4",
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
