apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-auth
data:
  APP_DEBUG: "false"
  APP_ENV: production
  APP_KEY: changeme
  APP_LOG_LEVEL: debug
  APP_NAME: "Laravel-Auth"
  APP_URL: https://www.laravel.com
  BROADCAST_DRIVER: pusher
  CACHE_DRIVER: redis
  QUEUE_DRIVER: redis
  SESSION_DRIVER: redis
  DB_CONNECTION: mysql
  DB_DATABASE: laravelauth
  DB_HOST: host
  DB_PASSWORD: password
  DB_PORT: "3306"
  DB_USERNAME: username
  REDIS_HOST: redis
  REDIS_PORT: "6379"